# 指明依赖库的来源地址
# source 'https://github.com/CocoaPods/Specs.git'

# 说明平台是ios，版本是11.0
platform:ios,'11.0'

# 忽略引入库的所有警告（强迫症者的福音啊）
inhibit_all_warnings!

# Uncomment the next line if you're using Swift or would like to use dynamic 	frameworks
use_frameworks!

target 'HSTransitionDemo' do

  pod 'HSTransition', :path => '../'

  target 'HSTransitionDemoTests' do
    inherit! :search_paths

  end
end
